# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$(document).ready ->
  $('#classic').click ->
    $('.grid').removeClass 'black'
    $('#wrapper').empty().removeClass 'black'
    div = $('<div class="grid"></div>')
    input = Number(window.prompt('Please enter grid size', '32'))
    size = Math.floor(960 / input) - 2
    count = 0
    squared = input * input
    while count < squared
      $(div).last().clone().appendTo '#wrapper'
      count++
    $('.grid').height(size).width size
    $('.grid').hover ->
      $(this).addClass 'black'
      return
    return
  $('#gradient').click ->
    $('.grid').removeClass 'black'
    $('#wrapper').empty().addClass 'black'
    div = $('<div class="grid"></div>')
    input = Number(window.prompt('Please enter grid size', '32'))
    size = Math.floor(960 / input) - 2
    count = 0
    squared = input * input
    while count < squared
      $(div).last().clone().appendTo '#wrapper'
      count++
    $('.grid').height(size).width(size).css 'background-color', 'white'
    $('.grid').mouseenter ->
      gradient = $(this).css('opacity')
      if gradient > 0
        $(this).css 'opacity', '-=0.1'
        console.log gradient
      return
    return
  $('#rainbow').click ->
    $('.grid').removeClass 'black'
    $('#wrapper').empty().removeClass 'black'
    div = $('<div class="grid"></div>')
    input = Number(window.prompt('Please enter grid size', '32'))
    size = Math.floor(960 / input) - 2
    count = 0
    squared = input * input
    while count < squared
      $(div).last().clone().appendTo '#wrapper'
      count++
    $('.grid').height(size).width size
    $('.grid').hover ->

      random_color = ->
        '#' + Math.floor(Math.random() * 16777215).toString(16)

      $(this).css 'background-color', random_color
      return
    return
  return

# ---
# generated by js2coffee 2.2.0
